### ISSUE TITLE
weather not loading 

### ISSUE THREAD

**Issue by Jane2213** [danrabbit/nimbus#102]
![Screenshot from 2020-04-22 11 35 11](https://user-images.githubusercontent.com/46205771/80008499-77991e00-848d-11ea-87bb-4b1f65dd49ce.png)

**Comment by billythemonkey** [comment]
I have the same problem, but it also happens with GNOME Weather app...
![image](https://user-images.githubusercontent.com/66335306/83955355-fd103c00-a849-11ea-941f-6d6409192340.png)
It's in portuguese, but says forecast unavailable....

**Comment by danrabbit** [comment]
Closing as a duplicate of #96
