### ISSUE TITLE
Add CMake

### ISSUE THREAD

**Issue by btkostner** [danrabbit/nimbus#18]
I'm sorry to say that your application was denied on AppCenter due to incomplete packaging.

Uncompressing the `deb` file found [here](https://packages.elementary.io/testing/pool/main/c/com.github.danrabbit.nimbus/com.github.danrabbit.nimbus_0.1.0_amd64.deb) shows only the debian changelog file. No binary, appstream data, or icons. I'm going to assume this is because of meson.

**Comment by danrabbit** [comment]
Should be resolved in d5e35e8e5113bdb6343747d9988f1f2617bfdd3e
