### ISSUE TITLE
Unable to install Nimbus due to x86_64 not supported

### ISSUE THREAD

**Issue by babluboy** [danrabbit/nimbus#28]
Tried to install Nimbus and got this issue for not proceeding with the install...saw the same error with NaSC Caculator as well. Is this due to 64 bit not supported or some other specific issue with my laptop..

Here is the output of uname -a
Linux sid-Latitude-E4300 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Screenshot:
![screenshot from 2017-05-10 09 33 49](https://cloud.githubusercontent.com/assets/14061478/25890123/52072270-3564-11e7-8780-4abc9f80a3a3.jpeg)

**Comment by danrabbit** [comment]
Looks like you need to update your software sources.The AppCenter repo recently moved from `https` back to `http`

**Comment by babluboy** [comment]
Thanks for the info. To save me the trouble of searching is there a quick set of commands to switch to http

**Comment by danrabbit** [comment]
You'll need to edit your `/etc/apt/sources.list` and and change the deb line there
