### ISSUE TITLE
Switch between Celsius and Fahrenheit

### ISSUE THREAD

**Issue by luizaugustomm** [danrabbit/nimbus#29]
We don't use Fahrenheit in Brazil and in most part of the world.

I suggest Nimbus identify automatically user's location and changes temperature scale according to the current country. In addition, users could click in the temperature label to manually switch between scales.

**Comment by danrabbit** [comment]
Nimbus already pulls the setting from `org.gnome.GWeather temperature-unit`. I don't have any intention to add manual settings to Nimbus.
