### ISSUE TITLE
No close icon.

### ISSUE THREAD

**Issue by NobodyButMe** [danrabbit/nimbus#41]
Unlike within the image displayed on the GitHub page, the widget, when I run it, does not display a close button in the corner, rendering it unclosable without manually killing the process.

**Comment by danrabbit** [comment]
This was fixed in 4e8c6c7d0ea442117d6c67beeb08be8eea6cb2b4

**Comment by paoacc** [comment]
Ignoring closing behavior is so odd(my english is bad again)
"WTF you are not close?!?!?!!!" i mean(especially with #33)
