### ISSUE TITLE
Use civil twilight for color change

### ISSUE THREAD

**Issue by eliocamp** [danrabbit/nimbus#48]
As I write this, the sky outside is still illuminated but Nimbus has changed to a dark color and a Moon icon. I suppose this is because Nimbus uses the astronomical sunset as a reference point. It may be more appropriate to use the civil twilight, which probably coincides better with what people think of as "day" and "night".

**Comment by danrabbit** [comment]
Nimbus gets this data from GWeather, so this is an upstream issue there. Closing as "invalid" for Nimbus, since I can't change this in my codebase
