### ISSUE TITLE
feature request: Transparent widget/borderless mode

### ISSUE THREAD

**Issue by capstan1** [danrabbit/nimbus#51]
It would be neat to have a option to display Nimbus with transparent background and without borders. It would be even more "in the background" and only attract attention when I need to know the weather.

It could look like this: https://drive.google.com/open?id=0B2lRaFHoTHleWWJ2cW5qTzQyZEU

What do you think?

**Comment by danrabbit** [comment]
This kind of goes against one of the major design features of Nimbus which is the changing background. closing as "won't fix"
