### ISSUE TITLE
Redshift runs but doesn't work

### ISSUE THREAD

**Issue by pgrycz** [danrabbit/nimbus#55]
Redshift doesn't get location data, when trying to turn it off/on by options it popups with " Failed to run Redshift, Trying location provider `geoclue2'... " error window. When type 'top' command in terminal redshift-gtk is at the top eating 100% processor use. When I close the error window popup Redshift closes entirely...weird as I havent this issue previously like month ago when everything worked well.

**Comment by danrabbit** [comment]
This is not the repository for redshift. Closing as "Invalid" since this issue is not about Nimbus
