### ISSUE TITLE
Error 403 - Unable to get weather data

### ISSUE THREAD

**Issue by jrizzoli** [danrabbit/nimbus#72]
Installed on: eOS 0.4
Installed from: appCenter
Dependencies: geoclue-2.0 is installed
Repro steps: Open nibus > City is correctly located > No weather data (sun + "--" as temperature).
Logs: 
```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
(com.github.danrabbit.nimbus:7188): GWeather-WARNING **: Failed to get IWIN forecast data: 403 Forbidden
```

**Comment by danrabbit** [comment]
Closing as a duplicate of #30
